services:
  nginx:
    build: nginx
    restart: always
    ports:
      - "7001:80"
  mysql:
    image: mariadb
    restart: always
    depends_on:
      - nginx
    volumes:
      - './database:/var/lib/mysql'
  phpmyadmin:
    image: phpmyadmin
    restart: always
    depends_on:
      - nginx
      - mysql
    environment:
      PMA_HOST: mysql
  frontend:
    build: frontend
    restart: always
    depends_on:
      - nginx
      - backend
  backend:
    build: backend
    restart: always
    depends_on:
      - nginx
      - mysql
    environment:
      PORT: 9000
      LOG_LEVEL: "debug"
